COMMON_CODE = {
    "100": "Token expired",
    "101": "Password expired",
    "102": "Login ID and password is not matching",
    "103": "Password incorrect",
    "104": "Login ID incorrect",
    "105": "Device type incorrect",
    "106": "Password requires 8 characters or more and has at least 1 alphabet letter",
    "107": "DOB incorrect",
    "108": "noti_id not exist",
    "109": "account_id not exist",
    "110": "Your current Margin Level is not allowed to withdraw. "
    "Please close some positions if you want to make a different request!",
    "111": "Your Margin Level is nearly the Margin Call Level",
    "112": "Minimum amount is not below {0}",
    "113": "Maximum withdrawal amount is not above the withdrawable amount",
    "114": "{0} is required",
    "115": "{0} wrong format",
    "116": "postalcode not exist",
    "117": "Email expired",
    "118": "Email existed",
    "119": "",
    "120": "",
    "121": "全てチェックされていないと、お客様情報以下の項目を登録出来ない。",
    "122": "20歳以上75歳未満が必要です",
    "123": "年収が150万円以下の場合は、口座開設できません。",
}
